# Generated by Django 4.0.2 on 2022-04-17 16:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('drazba', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='predmet',
            name='exekutor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='drazba.exekutor', verbose_name='Exekutor'),
        ),
    ]
