# Generated by Django 5.1.7 on 2025-05-04 15:39

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drazba', '0002_predmet_exekutor'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Zajemce',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telefon', models.CharField(error_messages={'blank': 'Pole nesmí být prázdné', 'invalid': 'Neplatné telefonní číslo'}, help_text='Telefonní číslo ve tvaru: +420 123 456 789', max_length=16, validators=[django.core.validators.RegexValidator('^[+]\\d{3}( \\d{3}){3}$', 'Nesprávně zadané telefonní číslo')], verbose_name='Telefon')),
                ('datum_registrace', models.DateTimeField(auto_now_add=True, verbose_name='Datum registrace')),
                ('typ', models.CharField(choices=[('FO', 'Fyzická osoba'), ('PO', 'Právnická osoba')], max_length=2, verbose_name='Typ zájemce')),
                ('poznamka', models.TextField(blank=True, null=True, verbose_name='Poznámka')),
                ('predmety', models.ManyToManyField(related_name='zajemci', to='drazba.predmet', verbose_name='Předměty zájmu')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Uživatel')),
            ],
            options={
                'verbose_name': 'Zájemce',
                'verbose_name_plural': 'Zájemci',
                'ordering': ['datum_registrace'],
            },
        ),
    ]
